services:
  app:
    build: .
    container_name: grant_scraper_app
    depends_on:
      selenium-hub:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    command: tail -f /dev/null
    #python app/main.py
    ports:
      - "8080:5000"

  db:
    image: postgres:15
    container_name: postgres_opportunities
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_grants
    platform: linux/amd64
    ports:
      - "6379:6379"

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium_hub
    ports:
      - "4444:4444"  
      - "4442:4442"  
      - "4443:4443"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 30

  chrome-node:
    image: seleniarm/node-chromium:latest
    container_name: chrome_node
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_ENABLED=true
    ports:
      - "7900:7900"

volumes:
  pgdata:
