version: 1
synonyms:
  visual art: Visual Arts
  visual art and filmmaking: Film Making
  film: Film Making
  filmmaking: Film Making
  films: Film Making
  movie: Film Making
  movies: Film Making
  houston-based: Houston
  south asian: South Asian
  cultural heritage: Cultural Heritage
  community engagement: Community Engagement
  civic engagement: Community Engagement
  music: Music
  musical: Music
  musician: Music
  qawwali music: Qawwali
  qawwali: Qawwali
  arts education: Arts
  arts and culture: Arts
  folk arts: Arts
  artist-led: Arts
  artist residency: Arts
  artist residencies: Arts
  artist fellowship: Arts
  general operating support: Arts
  capacity building: Arts
  infrastructure funding: Arts
  emerging organizations: Arts
  multi-year: Arts
  storytelling: Arts
  traditional music: Music
  folk music: Music
  devotional music: Music
  bhakti: Music
  sufi: Music
  ethnomusicology: Music
  healing through music: Music
  cultural organizing: Community Engagement
  cultural strategy: Community Engagement
  cross-cultural: Community Engagement
  intercultural: Community Engagement
  interfaith: Community Engagement
  religious pluralism: Community Engagement
  cross-racial: Community Engagement
  bridge-building: Community Engagement
  immigrant communities: Community Engagement
  minority communities: Community Engagement
  bipoc: Community Engagement
  aapi: Community Engagement
  desi community: Community Engagement
  youth-led: Community Engagement
  youth: Community Engagement
  storytelling for justice: Community Engagement
  narrative change: Community Engagement
  voter mobilization: Community Engagement
  get out the vote: Community Engagement
  gotv: Community Engagement
  voter education: Community Engagement
  ballot access: Community Engagement
  electoral justice: Community Engagement
  policy-focused art: Community Engagement
  power-building: Community Engagement
  grassroots: Community Engagement
  organizing: Community Engagement
  arts for democracy: Community Engagement
  civic artist: Community Engagement
  civic artist fellowship: Community Engagement
  trauma-informed: Community Engagement
  social cohesion: Community Engagement
  cross-sector: Community Engagement
  cultural sustainability: Community Engagement
  language preservation: Community Engagement
  Civic engagement: Community Engagement
  Community building: Community Engagement
