sites:
  - name: fresharts
    url: https://fresharts.org/artist-opportunity-board-2/
    iframe: true
    scroll: true
    scraper_class: FreshArtsScraper  
    tabs:
      - label: "Grant"
      - label: "Call for Entry"
    opportunity_selector: "ul.opportunity-grid > li"
    card_class: "opportunity-item"
    title_class: "opportunity-card-title"
    description_class: "description-text"
    tags_selector: ".small-text.grey-text"
    opportunity_base_url: "https://fleato.com"

  - name: creativecapital
    url: https://creative-capital.org/category/artist-opportunities/
    scroll: true
    scraper_class: CreativeCapitalScraper
    desktop_filters: "filter-desktop"
    opportunity_selector: "a.item"
    title_selector: ".item-title h3"
    description_selector: ".item-desc p"
    deadline_selector: ".item-info span"
    next_button_selector: ".pagination-btn.next"
    accordion_selectors: ["#collapseOne2", "#collapseTwo2"]  
    checkbox_ids_desktop: ["desktop-grant", "desktop-texas"]
    checkbox_ids_mobile: ["mob-grant", "mob-texas"]        
  
  - name: surdna
    url: https://surdna.org/grants-database/
    scroll: true
    scraper_class: SurdnaScraper
    row_selector: "table tbody tr"
    cell_tag: "td"
    org_link_selector: "a"
    description_selector: ".project-summary p"
    next_button_selector: "a.next.page-numbers"
  
  - name: pickuptheflow
    url: https://pickuptheflow.org/
    scroll: true
    scraper_class: PickupTheFlowScraper
    article_selector: "article.post"
    date_selector: "div.entry-date time"
    link_selector: "h2.entry-title a"
    title_selector: "h1.entry-title"
    image_selector: "article img"


